# Legacy manual configuration for Tududi custom panel in Home Assistant
# NOTE: This is no longer needed when using the config flow integration!
# The new integration automatically handles panel registration.

# If you want to manually configure (not recommended):
# panel_custom:
#   - name: tududi_hacs
#     sidebar_title: Tududi
#     sidebar_icon: mdi:clipboard-text
#     url_path: tududi
#     module_url: /local/tududi_hacs/panel.html
#     embed_iframe: true
#     require_admin: false
