name: Label Enhancement by Title

permissions:
  issues: write
  pull-requests: write
  contents: read

on:
  issues:
    types: [opened, edited]

jobs:
  label_bug:
    runs-on: ubuntu-latest
    steps:
      - name: Check for keyword and label
        uses: actions/github-script@v7
        with:
          script: |
            const keyword = "feat"; // Change this to your word
            const labelToAdd = "enhancement"; // Change to your desired label

            const title = context.payload.issue.title.toLowerCase();
            if (title.includes(keyword)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: [labelToAdd]
              });
            }